# Generated by Django 5.2 on 2025-04-27 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=255)),
                ('numero', models.IntegerField()),
                ('bairro', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=255)),
                ('municipio', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Assistida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registro.endereco')),
            ],
        ),
        migrations.CreateModel(
            name='Agressor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registro.endereco')),
            ],
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_ocorrencia', models.CharField(default='Local não informado', max_length=300)),
                ('tipo', models.CharField(default='Tipo não informado', max_length=300)),
                ('relacao_vitima_autor', models.CharField(blank=True, max_length=300, null=True)),
                ('agressor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='registro.agressor')),
                ('assistida', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='registro.assistida')),
            ],
            options={
                'db_table': 'ocorrencias',
            },
        ),
    ]
