# Generated by Django 5.2 on 2025-05-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OcorrenciaImportada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_assistida', models.CharField(max_length=255)),
                ('nome_agressor', models.CharField(max_length=255)),
                ('local_ocorrencia', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('relacao_vitima_autor', models.CharField(blank=True, max_length=255, null=True)),
                ('data_ocorrencia', models.DateField(blank=True, null=True)),
                ('rua_assistida', models.CharField(max_length=255)),
                ('numero_assistida', models.CharField(max_length=10)),
                ('bairro_assistida', models.CharField(max_length=100)),
                ('cidade_assistida', models.CharField(max_length=100)),
                ('municipio_assistida', models.CharField(max_length=100)),
                ('rua_agressor', models.CharField(max_length=255)),
                ('numero_agressor', models.CharField(max_length=10)),
                ('bairro_agressor', models.CharField(max_length=100)),
                ('cidade_agressor', models.CharField(max_length=100)),
                ('municipio_agressor', models.CharField(max_length=100)),
                ('data_importacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ocorrencias',
            },
        ),
    ]
