# Generated by Django 5.2.6 on 2025-09-09 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agressor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('relacao_com_assistida', models.CharField(blank=True, max_length=100, null=True)),
                ('rua', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'agressores',
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_alerta', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('data_hora_alerta', models.DateTimeField(auto_now_add=True)),
                ('localidade_alvo', models.CharField(max_length=100)),
                ('status_email_enviado', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'alertas',
            },
        ),
        migrations.CreateModel(
            name='Assistida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=50, null=True)),
                ('escolaridade', models.CharField(blank=True, max_length=100, null=True)),
                ('profissao', models.CharField(blank=True, max_length=100, null=True)),
                ('rua', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'assistidas',
            },
        ),
        migrations.CreateModel(
            name='PerfilAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_perfil', models.CharField(max_length=50, unique=True)),
                ('permissoes_json', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'perfis_acesso',
            },
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_ocorrencia', models.CharField(max_length=255)),
                ('data_ocorrencia', models.DateField()),
                ('tipo_violencia', models.CharField(max_length=255)),
                ('descricao_fato', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('data_importacao', models.DateTimeField(auto_now_add=True)),
                ('apagado', models.BooleanField(default=False)),
                ('agressor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='registro.agressor')),
                ('assistida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='registro.assistida')),
            ],
            options={
                'db_table': 'ocorrencias',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha_hash', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('perfil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registro.perfilacesso')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
