# Generated by Django 5.2.6 on 2025-09-09 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocorrencia',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='longitude',
        ),
    ]
