# Generated by Django 5.2 on 2025-04-28 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agressor',
            options={'verbose_name': 'Agressor', 'verbose_name_plural': 'Agressores'},
        ),
        migrations.AlterModelOptions(
            name='assistida',
            options={'verbose_name': 'Assistida', 'verbose_name_plural': 'Assistidas'},
        ),
        migrations.AlterModelOptions(
            name='endereco',
            options={'verbose_name': 'Endereço', 'verbose_name_plural': 'Endereços'},
        ),
        migrations.AlterModelOptions(
            name='ocorrencia',
            options={'verbose_name': 'Ocorrência', 'verbose_name_plural': 'Ocorrências'},
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='data_ocorrencia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='assistida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registro.assistida'),
        ),
    ]
