# Generated by Django 5.2 on 2025-05-21 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrenciaimportada',
            name='apagado',
            field=models.BooleanField(default=False),
        ),
    ]
