# Generated by Django 5.2.7 on 2025-10-11 14:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_remove_ocorrencia_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocorrencia',
            name='assistida',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='perfil',
        ),
        migrations.AlterModelOptions(
            name='agressor',
            options={'verbose_name': 'Agressor', 'verbose_name_plural': 'Agressores'},
        ),
        migrations.AlterModelOptions(
            name='alerta',
            options={'ordering': ['-data_hora_alerta'], 'verbose_name': 'Alerta', 'verbose_name_plural': 'Alertas'},
        ),
        migrations.AlterModelOptions(
            name='ocorrencia',
            options={'ordering': ['-data_registro', '-id'], 'verbose_name': 'Ocorrência', 'verbose_name_plural': 'Ocorrências'},
        ),
        migrations.RenameField(
            model_name='ocorrencia',
            old_name='data_importacao',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='agressor',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='agressor',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='agressor',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='agressor',
            name='municipio',
        ),
        migrations.RemoveField(
            model_name='agressor',
            name='nome_completo',
        ),
        migrations.RemoveField(
            model_name='agressor',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='agressor',
            name='relacao_com_assistida',
        ),
        migrations.RemoveField(
            model_name='agressor',
            name='rua',
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='agressor',
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='apagado',
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='data_ocorrencia',
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='descricao_fato',
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='local_ocorrencia',
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='tipo_violencia',
        ),
        migrations.AddField(
            model_name='agressor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agressor',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='agressor',
            name='ocorrencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agressores', to='registro.ocorrencia'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='data_registro',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Data do registro'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='envolvidos_raw',
            field=models.TextField(blank=True, null=True, verbose_name='Envolvidos (raw)'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='municipio',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Município'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='natureza',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Natureza da ocorrência'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='numero_procedimento',
            field=models.CharField(db_index=True, default='0000/0000', max_length=120, verbose_name='Número do procedimento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='parsed_envolvidos',
            field=models.JSONField(blank=True, null=True, verbose_name='Envolvidos (parsed)'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='processed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Processado'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='unidade_apuracao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Unidade de apuração'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='unidade_registro',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Unidade de registro'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='data_hora_alerta',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora do alerta'),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='localidade_alvo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Localidade alvo'),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='status_email_enviado',
            field=models.BooleanField(default=False, verbose_name='E-mail enviado'),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='titulo_alerta',
            field=models.CharField(max_length=255, verbose_name='Título do alerta'),
        ),
        migrations.AlterModelTable(
            name='agressor',
            table=None,
        ),
        migrations.AlterModelTable(
            name='ocorrencia',
            table=None,
        ),
        migrations.CreateModel(
            name='Vitima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitimas', to='registro.ocorrencia')),
            ],
            options={
                'verbose_name': 'Vítima',
                'verbose_name_plural': 'Vítimas',
            },
        ),
        migrations.DeleteModel(
            name='Assistida',
        ),
        migrations.DeleteModel(
            name='PerfilAcesso',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
