# Generated by Django 5.2 on 2025-05-21 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_ocorrenciaimportada_apagado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrenciaimportada',
            name='numero_agressor',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ocorrenciaimportada',
            name='numero_assistida',
            field=models.CharField(max_length=20),
        ),
    ]
