# Generated by Django 5.2 on 2025-05-21 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_alter_ocorrenciaimportada_numero_agressor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ocorrenciaimportada',
            old_name='bairro_assistida',
            new_name='bairro_vitima',
        ),
        migrations.RenameField(
            model_name='ocorrenciaimportada',
            old_name='cidade_assistida',
            new_name='cidade_vitima',
        ),
        migrations.RenameField(
            model_name='ocorrenciaimportada',
            old_name='municipio_assistida',
            new_name='municipio_vitima',
        ),
        migrations.RenameField(
            model_name='ocorrenciaimportada',
            old_name='nome_assistida',
            new_name='nome_vitima',
        ),
        migrations.RenameField(
            model_name='ocorrenciaimportada',
            old_name='numero_assistida',
            new_name='numero_vitima',
        ),
        migrations.RenameField(
            model_name='ocorrenciaimportada',
            old_name='rua_assistida',
            new_name='rua_vitima',
        ),
    ]
