# Generated by Django 5.2.7 on 2025-10-17 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_remove_ocorrencia_assistida_remove_usuario_perfil_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ocorrencia',
            options={'ordering': ['municipio', 'data_registro'], 'verbose_name': 'Ocorrência', 'verbose_name_plural': 'Ocorrências'},
        ),
    ]
