# Generated by Django 5.2.7 on 2025-10-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_alter_ocorrencia_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agressor',
            name='ocorrencia',
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='agressores',
            field=models.ManyToManyField(related_name='ocorrencias', to='registro.agressor'),
        ),
    ]
