# Generated by Django 5.2.7 on 2025-11-03 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_remove_agressor_ocorrencia_ocorrencia_agressores'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='medida_protetiva',
            field=models.BooleanField(default=False, verbose_name='Possui medida protetiva?'),
        ),
    ]
