# Generated by Django 5.2.7 on 2025-11-13 15:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0006_ocorrencia_medida_protetiva'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alerta',
            options={},
        ),
        migrations.RemoveField(
            model_name='alerta',
            name='data_hora_alerta',
        ),
        migrations.RemoveField(
            model_name='alerta',
            name='localidade_alvo',
        ),
        migrations.RemoveField(
            model_name='alerta',
            name='status_email_enviado',
        ),
        migrations.RemoveField(
            model_name='alerta',
            name='titulo_alerta',
        ),
        migrations.AddField(
            model_name='alerta',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='alerta',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='alerta',
            name='tipo',
            field=models.CharField(choices=[('VITIMA_REINCIDENTE', 'Vítima Reincidente'), ('AGRESSOR_REINCIDENTE', 'Agressor Reincidente'), ('CRESCIMENTO_MENSAL', 'Crescimento Mensal')], default='geral', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alerta',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterModelTable(
            name='alerta',
            table=None,
        ),
    ]
